data = read.table("data.txt")
print(nrow(data))
print(data[10,])
data.lm = lm(V2 ~ V1, data=data)
print(round(unname(coef(data.lm)[1]), 3))
print(round(unname(coef(data.lm)[2]), 3))
print(round(summary(data.lm)$coefficients[2, 3], 3))
print(round(summary(data.lm)$r.squared, 3))
print(predict(data.lm, newdata = data.frame(V1 = data$V1[10]), interval = "confidence", level = 0.95))
print(predict(data.lm, newdata = data.frame(V1 = data$V1[10]), interval = "prediction", level = 0.95))

bmp(file = "res.bmp")
plot(data$V1, rstandard(data.lm), ylab="Standardized Residual", xlab="V1", main="Standardized Residuals")
abline(0, 0)
dev.off()
